// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/roundtrip_time_messages.proto

package de.uniluebeck.itm.uberlay.core.protocols.rtt;

public final class RoundtripTimeMessages {
  private RoundtripTimeMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class RoundtripTimeRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RoundtripTimeRequest.newBuilder() to construct.
    private RoundtripTimeRequest() {
      initFields();
    }
    private RoundtripTimeRequest(boolean noInit) {}
    
    private static final RoundtripTimeRequest defaultInstance;
    public static RoundtripTimeRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoundtripTimeRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_fieldAccessorTable;
    }
    
    // required uint64 unix_epoch_in_millis = 1;
    public static final int UNIX_EPOCH_IN_MILLIS_FIELD_NUMBER = 1;
    private boolean hasUnixEpochInMillis;
    private long unixEpochInMillis_ = 0L;
    public boolean hasUnixEpochInMillis() { return hasUnixEpochInMillis; }
    public long getUnixEpochInMillis() { return unixEpochInMillis_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasUnixEpochInMillis) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasUnixEpochInMillis()) {
        output.writeUInt64(1, getUnixEpochInMillis());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasUnixEpochInMillis()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getUnixEpochInMillis());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest result;
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest();
        return builder;
      }
      
      protected de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.getDefaultInstance()) return this;
        if (other.hasUnixEpochInMillis()) {
          setUnixEpochInMillis(other.getUnixEpochInMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setUnixEpochInMillis(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required uint64 unix_epoch_in_millis = 1;
      public boolean hasUnixEpochInMillis() {
        return result.hasUnixEpochInMillis();
      }
      public long getUnixEpochInMillis() {
        return result.getUnixEpochInMillis();
      }
      public Builder setUnixEpochInMillis(long value) {
        result.hasUnixEpochInMillis = true;
        result.unixEpochInMillis_ = value;
        return this;
      }
      public Builder clearUnixEpochInMillis() {
        result.hasUnixEpochInMillis = false;
        result.unixEpochInMillis_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeRequest)
    }
    
    static {
      defaultInstance = new RoundtripTimeRequest(true);
      de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeRequest)
  }
  
  public static final class RoundtripTimeResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RoundtripTimeResponse.newBuilder() to construct.
    private RoundtripTimeResponse() {
      initFields();
    }
    private RoundtripTimeResponse(boolean noInit) {}
    
    private static final RoundtripTimeResponse defaultInstance;
    public static RoundtripTimeResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoundtripTimeResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_fieldAccessorTable;
    }
    
    // required uint64 request_unix_epoch_in_millis = 1;
    public static final int REQUEST_UNIX_EPOCH_IN_MILLIS_FIELD_NUMBER = 1;
    private boolean hasRequestUnixEpochInMillis;
    private long requestUnixEpochInMillis_ = 0L;
    public boolean hasRequestUnixEpochInMillis() { return hasRequestUnixEpochInMillis; }
    public long getRequestUnixEpochInMillis() { return requestUnixEpochInMillis_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasRequestUnixEpochInMillis) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRequestUnixEpochInMillis()) {
        output.writeUInt64(1, getRequestUnixEpochInMillis());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequestUnixEpochInMillis()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getRequestUnixEpochInMillis());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse result;
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse();
        return builder;
      }
      
      protected de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.getDefaultInstance()) return this;
        if (other.hasRequestUnixEpochInMillis()) {
          setRequestUnixEpochInMillis(other.getRequestUnixEpochInMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRequestUnixEpochInMillis(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required uint64 request_unix_epoch_in_millis = 1;
      public boolean hasRequestUnixEpochInMillis() {
        return result.hasRequestUnixEpochInMillis();
      }
      public long getRequestUnixEpochInMillis() {
        return result.getRequestUnixEpochInMillis();
      }
      public Builder setRequestUnixEpochInMillis(long value) {
        result.hasRequestUnixEpochInMillis = true;
        result.requestUnixEpochInMillis_ = value;
        return this;
      }
      public Builder clearRequestUnixEpochInMillis() {
        result.hasRequestUnixEpochInMillis = false;
        result.requestUnixEpochInMillis_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeResponse)
    }
    
    static {
      defaultInstance = new RoundtripTimeResponse(true);
      de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/resources/roundtrip_time_mess" +
      "ages.proto\022,de.uniluebeck.itm.uberlay.co" +
      "re.protocols.rtt\"4\n\024RoundtripTimeRequest" +
      "\022\034\n\024unix_epoch_in_millis\030\001 \002(\004\"=\n\025Roundt" +
      "ripTimeResponse\022$\n\034request_unix_epoch_in" +
      "_millis\030\001 \002(\004B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor,
              new java.lang.String[] { "UnixEpochInMillis", },
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.class,
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.Builder.class);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor,
              new java.lang.String[] { "RequestUnixEpochInMillis", },
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.class,
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
