// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/roundtrip_time_messages.proto

package de.uniluebeck.itm.uberlay.core.protocols.rtt;

public final class RoundtripTimeMessages {
  private RoundtripTimeMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RoundtripTimeRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 unix_epoch_in_millis = 1;
    boolean hasUnixEpochInMillis();
    long getUnixEpochInMillis();
  }
  public static final class RoundtripTimeRequest extends
      com.google.protobuf.GeneratedMessage
      implements RoundtripTimeRequestOrBuilder {
    // Use RoundtripTimeRequest.newBuilder() to construct.
    private RoundtripTimeRequest(Builder builder) {
      super(builder);
    }
    private RoundtripTimeRequest(boolean noInit) {}
    
    private static final RoundtripTimeRequest defaultInstance;
    public static RoundtripTimeRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoundtripTimeRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 unix_epoch_in_millis = 1;
    public static final int UNIX_EPOCH_IN_MILLIS_FIELD_NUMBER = 1;
    private long unixEpochInMillis_;
    public boolean hasUnixEpochInMillis() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getUnixEpochInMillis() {
      return unixEpochInMillis_;
    }
    
    private void initFields() {
      unixEpochInMillis_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUnixEpochInMillis()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, unixEpochInMillis_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, unixEpochInMillis_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_fieldAccessorTable;
      }
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        unixEpochInMillis_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.getDefaultInstance();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest build() {
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest buildPartial() {
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest result = new de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixEpochInMillis_ = unixEpochInMillis_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.getDefaultInstance()) return this;
        if (other.hasUnixEpochInMillis()) {
          setUnixEpochInMillis(other.getUnixEpochInMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUnixEpochInMillis()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixEpochInMillis_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 unix_epoch_in_millis = 1;
      private long unixEpochInMillis_ ;
      public boolean hasUnixEpochInMillis() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getUnixEpochInMillis() {
        return unixEpochInMillis_;
      }
      public Builder setUnixEpochInMillis(long value) {
        bitField0_ |= 0x00000001;
        unixEpochInMillis_ = value;
        onChanged();
        return this;
      }
      public Builder clearUnixEpochInMillis() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixEpochInMillis_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeRequest)
    }
    
    static {
      defaultInstance = new RoundtripTimeRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeRequest)
  }
  
  public interface RoundtripTimeResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 request_unix_epoch_in_millis = 1;
    boolean hasRequestUnixEpochInMillis();
    long getRequestUnixEpochInMillis();
  }
  public static final class RoundtripTimeResponse extends
      com.google.protobuf.GeneratedMessage
      implements RoundtripTimeResponseOrBuilder {
    // Use RoundtripTimeResponse.newBuilder() to construct.
    private RoundtripTimeResponse(Builder builder) {
      super(builder);
    }
    private RoundtripTimeResponse(boolean noInit) {}
    
    private static final RoundtripTimeResponse defaultInstance;
    public static RoundtripTimeResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoundtripTimeResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 request_unix_epoch_in_millis = 1;
    public static final int REQUEST_UNIX_EPOCH_IN_MILLIS_FIELD_NUMBER = 1;
    private long requestUnixEpochInMillis_;
    public boolean hasRequestUnixEpochInMillis() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getRequestUnixEpochInMillis() {
      return requestUnixEpochInMillis_;
    }
    
    private void initFields() {
      requestUnixEpochInMillis_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestUnixEpochInMillis()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, requestUnixEpochInMillis_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, requestUnixEpochInMillis_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_fieldAccessorTable;
      }
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestUnixEpochInMillis_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.getDefaultInstance();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse build() {
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse buildPartial() {
        de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse result = new de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestUnixEpochInMillis_ = requestUnixEpochInMillis_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.getDefaultInstance()) return this;
        if (other.hasRequestUnixEpochInMillis()) {
          setRequestUnixEpochInMillis(other.getRequestUnixEpochInMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestUnixEpochInMillis()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestUnixEpochInMillis_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 request_unix_epoch_in_millis = 1;
      private long requestUnixEpochInMillis_ ;
      public boolean hasRequestUnixEpochInMillis() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getRequestUnixEpochInMillis() {
        return requestUnixEpochInMillis_;
      }
      public Builder setRequestUnixEpochInMillis(long value) {
        bitField0_ |= 0x00000001;
        requestUnixEpochInMillis_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestUnixEpochInMillis() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestUnixEpochInMillis_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeResponse)
    }
    
    static {
      defaultInstance = new RoundtripTimeResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/resources/roundtrip_time_mess" +
      "ages.proto\022,de.uniluebeck.itm.uberlay.co" +
      "re.protocols.rtt\"4\n\024RoundtripTimeRequest" +
      "\022\034\n\024unix_epoch_in_millis\030\001 \002(\004\"=\n\025Roundt" +
      "ripTimeResponse\022$\n\034request_unix_epoch_in" +
      "_millis\030\001 \002(\004B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeRequest_descriptor,
              new java.lang.String[] { "UnixEpochInMillis", },
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.class,
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeRequest.Builder.class);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_rtt_RoundtripTimeResponse_descriptor,
              new java.lang.String[] { "RequestUnixEpochInMillis", },
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.class,
              de.uniluebeck.itm.uberlay.core.protocols.rtt.RoundtripTimeMessages.RoundtripTimeResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
