// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/path_vector_messages.proto

package de.uniluebeck.itm.uberlay.core.protocols.pvp;

public final class PathVectorMessages {
  private PathVectorMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PathVectorUpdate extends
      com.google.protobuf.GeneratedMessage {
    // Use PathVectorUpdate.newBuilder() to construct.
    private PathVectorUpdate() {
      initFields();
    }
    private PathVectorUpdate(boolean noInit) {}
    
    private static final PathVectorUpdate defaultInstance;
    public static PathVectorUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public PathVectorUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_fieldAccessorTable;
    }
    
    public static final class RoutingTableEntry extends
        com.google.protobuf.GeneratedMessage {
      // Use RoutingTableEntry.newBuilder() to construct.
      private RoutingTableEntry() {
        initFields();
      }
      private RoutingTableEntry(boolean noInit) {}
      
      private static final RoutingTableEntry defaultInstance;
      public static RoutingTableEntry getDefaultInstance() {
        return defaultInstance;
      }
      
      public RoutingTableEntry getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_fieldAccessorTable;
      }
      
      // required string destination = 1;
      public static final int DESTINATION_FIELD_NUMBER = 1;
      private boolean hasDestination;
      private java.lang.String destination_ = "";
      public boolean hasDestination() { return hasDestination; }
      public java.lang.String getDestination() { return destination_; }
      
      // required int64 cost = 2;
      public static final int COST_FIELD_NUMBER = 2;
      private boolean hasCost;
      private long cost_ = 0L;
      public boolean hasCost() { return hasCost; }
      public long getCost() { return cost_; }
      
      // repeated string path = 3;
      public static final int PATH_FIELD_NUMBER = 3;
      private java.util.List<java.lang.String> path_ =
        java.util.Collections.emptyList();
      public java.util.List<java.lang.String> getPathList() {
        return path_;
      }
      public int getPathCount() { return path_.size(); }
      public java.lang.String getPath(int index) {
        return path_.get(index);
      }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasDestination) return false;
        if (!hasCost) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasDestination()) {
          output.writeString(1, getDestination());
        }
        if (hasCost()) {
          output.writeInt64(2, getCost());
        }
        for (java.lang.String element : getPathList()) {
          output.writeString(3, element);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasDestination()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getDestination());
        }
        if (hasCost()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, getCost());
        }
        {
          int dataSize = 0;
          for (java.lang.String element : getPathList()) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeStringSizeNoTag(element);
          }
          size += dataSize;
          size += 1 * getPathList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry result;
        
        // Construct using de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry();
          return builder;
        }
        
        protected de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDescriptor();
        }
        
        public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry getDefaultInstanceForType() {
          return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          if (result.path_ != java.util.Collections.EMPTY_LIST) {
            result.path_ =
              java.util.Collections.unmodifiableList(result.path_);
          }
          de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry) {
            return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry other) {
          if (other == de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDefaultInstance()) return this;
          if (other.hasDestination()) {
            setDestination(other.getDestination());
          }
          if (other.hasCost()) {
            setCost(other.getCost());
          }
          if (!other.path_.isEmpty()) {
            if (result.path_.isEmpty()) {
              result.path_ = new java.util.ArrayList<java.lang.String>();
            }
            result.path_.addAll(other.path_);
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setDestination(input.readString());
                break;
              }
              case 16: {
                setCost(input.readInt64());
                break;
              }
              case 26: {
                addPath(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string destination = 1;
        public boolean hasDestination() {
          return result.hasDestination();
        }
        public java.lang.String getDestination() {
          return result.getDestination();
        }
        public Builder setDestination(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasDestination = true;
          result.destination_ = value;
          return this;
        }
        public Builder clearDestination() {
          result.hasDestination = false;
          result.destination_ = getDefaultInstance().getDestination();
          return this;
        }
        
        // required int64 cost = 2;
        public boolean hasCost() {
          return result.hasCost();
        }
        public long getCost() {
          return result.getCost();
        }
        public Builder setCost(long value) {
          result.hasCost = true;
          result.cost_ = value;
          return this;
        }
        public Builder clearCost() {
          result.hasCost = false;
          result.cost_ = 0L;
          return this;
        }
        
        // repeated string path = 3;
        public java.util.List<java.lang.String> getPathList() {
          return java.util.Collections.unmodifiableList(result.path_);
        }
        public int getPathCount() {
          return result.getPathCount();
        }
        public java.lang.String getPath(int index) {
          return result.getPath(index);
        }
        public Builder setPath(int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.path_.set(index, value);
          return this;
        }
        public Builder addPath(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  if (result.path_.isEmpty()) {
            result.path_ = new java.util.ArrayList<java.lang.String>();
          }
          result.path_.add(value);
          return this;
        }
        public Builder addAllPath(
            java.lang.Iterable<? extends java.lang.String> values) {
          if (result.path_.isEmpty()) {
            result.path_ = new java.util.ArrayList<java.lang.String>();
          }
          super.addAll(values, result.path_);
          return this;
        }
        public Builder clearPath() {
          result.path_ = java.util.Collections.emptyList();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry)
      }
      
      static {
        defaultInstance = new RoutingTableEntry(true);
        de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry)
    }
    
    // required string sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private boolean hasSender;
    private java.lang.String sender_ = "";
    public boolean hasSender() { return hasSender; }
    public java.lang.String getSender() { return sender_; }
    
    // repeated .de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry routingTableEntries = 2;
    public static final int ROUTINGTABLEENTRIES_FIELD_NUMBER = 2;
    private java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> routingTableEntries_ =
      java.util.Collections.emptyList();
    public java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> getRoutingTableEntriesList() {
      return routingTableEntries_;
    }
    public int getRoutingTableEntriesCount() { return routingTableEntries_.size(); }
    public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry getRoutingTableEntries(int index) {
      return routingTableEntries_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasSender) return false;
      for (de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry element : getRoutingTableEntriesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSender()) {
        output.writeString(1, getSender());
      }
      for (de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry element : getRoutingTableEntriesList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSender()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSender());
      }
      for (de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry element : getRoutingTableEntriesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate result;
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate();
        return builder;
      }
      
      protected de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.routingTableEntries_ != java.util.Collections.EMPTY_LIST) {
          result.routingTableEntries_ =
            java.util.Collections.unmodifiableList(result.routingTableEntries_);
        }
        de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.getDefaultInstance()) return this;
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (!other.routingTableEntries_.isEmpty()) {
          if (result.routingTableEntries_.isEmpty()) {
            result.routingTableEntries_ = new java.util.ArrayList<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry>();
          }
          result.routingTableEntries_.addAll(other.routingTableEntries_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setSender(input.readString());
              break;
            }
            case 18: {
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder subBuilder = de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRoutingTableEntries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string sender = 1;
      public boolean hasSender() {
        return result.hasSender();
      }
      public java.lang.String getSender() {
        return result.getSender();
      }
      public Builder setSender(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSender = true;
        result.sender_ = value;
        return this;
      }
      public Builder clearSender() {
        result.hasSender = false;
        result.sender_ = getDefaultInstance().getSender();
        return this;
      }
      
      // repeated .de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry routingTableEntries = 2;
      public java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> getRoutingTableEntriesList() {
        return java.util.Collections.unmodifiableList(result.routingTableEntries_);
      }
      public int getRoutingTableEntriesCount() {
        return result.getRoutingTableEntriesCount();
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry getRoutingTableEntries(int index) {
        return result.getRoutingTableEntries(index);
      }
      public Builder setRoutingTableEntries(int index, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.routingTableEntries_.set(index, value);
        return this;
      }
      public Builder setRoutingTableEntries(int index, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder builderForValue) {
        result.routingTableEntries_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRoutingTableEntries(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.routingTableEntries_.isEmpty()) {
          result.routingTableEntries_ = new java.util.ArrayList<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry>();
        }
        result.routingTableEntries_.add(value);
        return this;
      }
      public Builder addRoutingTableEntries(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder builderForValue) {
        if (result.routingTableEntries_.isEmpty()) {
          result.routingTableEntries_ = new java.util.ArrayList<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry>();
        }
        result.routingTableEntries_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRoutingTableEntries(
          java.lang.Iterable<? extends de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> values) {
        if (result.routingTableEntries_.isEmpty()) {
          result.routingTableEntries_ = new java.util.ArrayList<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry>();
        }
        super.addAll(values, result.routingTableEntries_);
        return this;
      }
      public Builder clearRoutingTableEntries() {
        result.routingTableEntries_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate)
    }
    
    static {
      defaultInstance = new PathVectorUpdate(true);
      de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/path_vector_message" +
      "s.proto\022,de.uniluebeck.itm.uberlay.core." +
      "protocols.pvp\"\327\001\n\020PathVectorUpdate\022\016\n\006se" +
      "nder\030\001 \002(\t\022m\n\023routingTableEntries\030\002 \003(\0132" +
      "P.de.uniluebeck.itm.uberlay.core.protoco" +
      "ls.pvp.PathVectorUpdate.RoutingTableEntr" +
      "y\032D\n\021RoutingTableEntry\022\023\n\013destination\030\001 " +
      "\002(\t\022\014\n\004cost\030\002 \002(\003\022\014\n\004path\030\003 \003(\tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor,
              new java.lang.String[] { "Sender", "RoutingTableEntries", },
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.class,
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.Builder.class);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor =
            internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor.getNestedTypes().get(0);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor,
              new java.lang.String[] { "Destination", "Cost", "Path", },
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.class,
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
