// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/path_vector_messages.proto

package de.uniluebeck.itm.uberlay.core.protocols.pvp;

public final class PathVectorMessages {
  private PathVectorMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PathVectorUpdateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string sender = 1;
    boolean hasSender();
    String getSender();
    
    // repeated .de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry routingTableEntries = 2;
    java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> 
        getRoutingTableEntriesList();
    de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry getRoutingTableEntries(int index);
    int getRoutingTableEntriesCount();
    java.util.List<? extends de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder> 
        getRoutingTableEntriesOrBuilderList();
    de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder getRoutingTableEntriesOrBuilder(
        int index);
  }
  public static final class PathVectorUpdate extends
      com.google.protobuf.GeneratedMessage
      implements PathVectorUpdateOrBuilder {
    // Use PathVectorUpdate.newBuilder() to construct.
    private PathVectorUpdate(Builder builder) {
      super(builder);
    }
    private PathVectorUpdate(boolean noInit) {}
    
    private static final PathVectorUpdate defaultInstance;
    public static PathVectorUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public PathVectorUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_fieldAccessorTable;
    }
    
    public interface RoutingTableEntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string destination = 1;
      boolean hasDestination();
      String getDestination();
      
      // required int64 cost = 2;
      boolean hasCost();
      long getCost();
    }
    public static final class RoutingTableEntry extends
        com.google.protobuf.GeneratedMessage
        implements RoutingTableEntryOrBuilder {
      // Use RoutingTableEntry.newBuilder() to construct.
      private RoutingTableEntry(Builder builder) {
        super(builder);
      }
      private RoutingTableEntry(boolean noInit) {}
      
      private static final RoutingTableEntry defaultInstance;
      public static RoutingTableEntry getDefaultInstance() {
        return defaultInstance;
      }
      
      public RoutingTableEntry getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string destination = 1;
      public static final int DESTINATION_FIELD_NUMBER = 1;
      private java.lang.Object destination_;
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDestination() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            destination_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required int64 cost = 2;
      public static final int COST_FIELD_NUMBER = 2;
      private long cost_;
      public boolean hasCost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCost() {
        return cost_;
      }
      
      private void initFields() {
        destination_ = "";
        cost_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasDestination()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCost()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getDestinationBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, cost_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getDestinationBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, cost_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_fieldAccessorTable;
        }
        
        // Construct using de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          destination_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          cost_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDescriptor();
        }
        
        public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry getDefaultInstanceForType() {
          return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDefaultInstance();
        }
        
        public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry build() {
          de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry buildPartial() {
          de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.destination_ = destination_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.cost_ = cost_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry) {
            return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry other) {
          if (other == de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDefaultInstance()) return this;
          if (other.hasDestination()) {
            setDestination(other.getDestination());
          }
          if (other.hasCost()) {
            setCost(other.getCost());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasDestination()) {
            
            return false;
          }
          if (!hasCost()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                destination_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                cost_ = input.readInt64();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string destination = 1;
        private java.lang.Object destination_ = "";
        public boolean hasDestination() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getDestination() {
          java.lang.Object ref = destination_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            destination_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setDestination(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          destination_ = value;
          onChanged();
          return this;
        }
        public Builder clearDestination() {
          bitField0_ = (bitField0_ & ~0x00000001);
          destination_ = getDefaultInstance().getDestination();
          onChanged();
          return this;
        }
        void setDestination(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          destination_ = value;
          onChanged();
        }
        
        // required int64 cost = 2;
        private long cost_ ;
        public boolean hasCost() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public long getCost() {
          return cost_;
        }
        public Builder setCost(long value) {
          bitField0_ |= 0x00000002;
          cost_ = value;
          onChanged();
          return this;
        }
        public Builder clearCost() {
          bitField0_ = (bitField0_ & ~0x00000002);
          cost_ = 0L;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry)
      }
      
      static {
        defaultInstance = new RoutingTableEntry(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry)
    }
    
    private int bitField0_;
    // required string sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private java.lang.Object sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sender_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry routingTableEntries = 2;
    public static final int ROUTINGTABLEENTRIES_FIELD_NUMBER = 2;
    private java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> routingTableEntries_;
    public java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> getRoutingTableEntriesList() {
      return routingTableEntries_;
    }
    public java.util.List<? extends de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder> 
        getRoutingTableEntriesOrBuilderList() {
      return routingTableEntries_;
    }
    public int getRoutingTableEntriesCount() {
      return routingTableEntries_.size();
    }
    public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry getRoutingTableEntries(int index) {
      return routingTableEntries_.get(index);
    }
    public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder getRoutingTableEntriesOrBuilder(
        int index) {
      return routingTableEntries_.get(index);
    }
    
    private void initFields() {
      sender_ = "";
      routingTableEntries_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRoutingTableEntriesCount(); i++) {
        if (!getRoutingTableEntries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenderBytes());
      }
      for (int i = 0; i < routingTableEntries_.size(); i++) {
        output.writeMessage(2, routingTableEntries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenderBytes());
      }
      for (int i = 0; i < routingTableEntries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, routingTableEntries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_fieldAccessorTable;
      }
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoutingTableEntriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (routingTableEntriesBuilder_ == null) {
          routingTableEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          routingTableEntriesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.getDefaultInstance();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate build() {
        de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate buildPartial() {
        de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (routingTableEntriesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            routingTableEntries_ = java.util.Collections.unmodifiableList(routingTableEntries_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.routingTableEntries_ = routingTableEntries_;
        } else {
          result.routingTableEntries_ = routingTableEntriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.getDefaultInstance()) return this;
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (routingTableEntriesBuilder_ == null) {
          if (!other.routingTableEntries_.isEmpty()) {
            if (routingTableEntries_.isEmpty()) {
              routingTableEntries_ = other.routingTableEntries_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRoutingTableEntriesIsMutable();
              routingTableEntries_.addAll(other.routingTableEntries_);
            }
            onChanged();
          }
        } else {
          if (!other.routingTableEntries_.isEmpty()) {
            if (routingTableEntriesBuilder_.isEmpty()) {
              routingTableEntriesBuilder_.dispose();
              routingTableEntriesBuilder_ = null;
              routingTableEntries_ = other.routingTableEntries_;
              bitField0_ = (bitField0_ & ~0x00000002);
              routingTableEntriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoutingTableEntriesFieldBuilder() : null;
            } else {
              routingTableEntriesBuilder_.addAllMessages(other.routingTableEntries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        for (int i = 0; i < getRoutingTableEntriesCount(); i++) {
          if (!getRoutingTableEntries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sender_ = input.readBytes();
              break;
            }
            case 18: {
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder subBuilder = de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRoutingTableEntries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string sender = 1;
      private java.lang.Object sender_ = "";
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSender(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      void setSender(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
      }
      
      // repeated .de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate.RoutingTableEntry routingTableEntries = 2;
      private java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> routingTableEntries_ =
        java.util.Collections.emptyList();
      private void ensureRoutingTableEntriesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          routingTableEntries_ = new java.util.ArrayList<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry>(routingTableEntries_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder> routingTableEntriesBuilder_;
      
      public java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> getRoutingTableEntriesList() {
        if (routingTableEntriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routingTableEntries_);
        } else {
          return routingTableEntriesBuilder_.getMessageList();
        }
      }
      public int getRoutingTableEntriesCount() {
        if (routingTableEntriesBuilder_ == null) {
          return routingTableEntries_.size();
        } else {
          return routingTableEntriesBuilder_.getCount();
        }
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry getRoutingTableEntries(int index) {
        if (routingTableEntriesBuilder_ == null) {
          return routingTableEntries_.get(index);
        } else {
          return routingTableEntriesBuilder_.getMessage(index);
        }
      }
      public Builder setRoutingTableEntries(
          int index, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry value) {
        if (routingTableEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingTableEntriesIsMutable();
          routingTableEntries_.set(index, value);
          onChanged();
        } else {
          routingTableEntriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRoutingTableEntries(
          int index, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder builderForValue) {
        if (routingTableEntriesBuilder_ == null) {
          ensureRoutingTableEntriesIsMutable();
          routingTableEntries_.set(index, builderForValue.build());
          onChanged();
        } else {
          routingTableEntriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRoutingTableEntries(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry value) {
        if (routingTableEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingTableEntriesIsMutable();
          routingTableEntries_.add(value);
          onChanged();
        } else {
          routingTableEntriesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRoutingTableEntries(
          int index, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry value) {
        if (routingTableEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingTableEntriesIsMutable();
          routingTableEntries_.add(index, value);
          onChanged();
        } else {
          routingTableEntriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRoutingTableEntries(
          de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder builderForValue) {
        if (routingTableEntriesBuilder_ == null) {
          ensureRoutingTableEntriesIsMutable();
          routingTableEntries_.add(builderForValue.build());
          onChanged();
        } else {
          routingTableEntriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRoutingTableEntries(
          int index, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder builderForValue) {
        if (routingTableEntriesBuilder_ == null) {
          ensureRoutingTableEntriesIsMutable();
          routingTableEntries_.add(index, builderForValue.build());
          onChanged();
        } else {
          routingTableEntriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRoutingTableEntries(
          java.lang.Iterable<? extends de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry> values) {
        if (routingTableEntriesBuilder_ == null) {
          ensureRoutingTableEntriesIsMutable();
          super.addAll(values, routingTableEntries_);
          onChanged();
        } else {
          routingTableEntriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRoutingTableEntries() {
        if (routingTableEntriesBuilder_ == null) {
          routingTableEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          routingTableEntriesBuilder_.clear();
        }
        return this;
      }
      public Builder removeRoutingTableEntries(int index) {
        if (routingTableEntriesBuilder_ == null) {
          ensureRoutingTableEntriesIsMutable();
          routingTableEntries_.remove(index);
          onChanged();
        } else {
          routingTableEntriesBuilder_.remove(index);
        }
        return this;
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder getRoutingTableEntriesBuilder(
          int index) {
        return getRoutingTableEntriesFieldBuilder().getBuilder(index);
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder getRoutingTableEntriesOrBuilder(
          int index) {
        if (routingTableEntriesBuilder_ == null) {
          return routingTableEntries_.get(index);  } else {
          return routingTableEntriesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder> 
           getRoutingTableEntriesOrBuilderList() {
        if (routingTableEntriesBuilder_ != null) {
          return routingTableEntriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routingTableEntries_);
        }
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder addRoutingTableEntriesBuilder() {
        return getRoutingTableEntriesFieldBuilder().addBuilder(
            de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDefaultInstance());
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder addRoutingTableEntriesBuilder(
          int index) {
        return getRoutingTableEntriesFieldBuilder().addBuilder(
            index, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.getDefaultInstance());
      }
      public java.util.List<de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder> 
           getRoutingTableEntriesBuilderList() {
        return getRoutingTableEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder> 
          getRoutingTableEntriesFieldBuilder() {
        if (routingTableEntriesBuilder_ == null) {
          routingTableEntriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder, de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntryOrBuilder>(
                  routingTableEntries_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          routingTableEntries_ = null;
        }
        return routingTableEntriesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate)
    }
    
    static {
      defaultInstance = new PathVectorUpdate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorUpdate)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/path_vector_message" +
      "s.proto\022,de.uniluebeck.itm.uberlay.core." +
      "protocols.pvp\"\311\001\n\020PathVectorUpdate\022\016\n\006se" +
      "nder\030\001 \002(\t\022m\n\023routingTableEntries\030\002 \003(\0132" +
      "P.de.uniluebeck.itm.uberlay.core.protoco" +
      "ls.pvp.PathVectorUpdate.RoutingTableEntr" +
      "y\0326\n\021RoutingTableEntry\022\023\n\013destination\030\001 " +
      "\002(\t\022\014\n\004cost\030\002 \002(\003B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor,
              new java.lang.String[] { "Sender", "RoutingTableEntries", },
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.class,
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.Builder.class);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor =
            internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_descriptor.getNestedTypes().get(0);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorUpdate_RoutingTableEntry_descriptor,
              new java.lang.String[] { "Destination", "Cost", },
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.class,
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorMessages.PathVectorUpdate.RoutingTableEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
