// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/path_vector_protocol.proto

package de.uniluebeck.itm.uberlay.core.protocols.pvp;

public final class PathVectorProtocol {
  private PathVectorProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PathVectorProtocolRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use PathVectorProtocolRequest.newBuilder() to construct.
    private PathVectorProtocolRequest() {
      initFields();
    }
    private PathVectorProtocolRequest(boolean noInit) {}
    
    private static final PathVectorProtocolRequest defaultInstance;
    public static PathVectorProtocolRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PathVectorProtocolRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest result;
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest();
        return builder;
      }
      
      protected de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocolRequest)
    }
    
    static {
      defaultInstance = new PathVectorProtocolRequest(true);
      de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocolRequest)
  }
  
  public static final class PathVectorProtocolResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use PathVectorProtocolResponse.newBuilder() to construct.
    private PathVectorProtocolResponse() {
      initFields();
    }
    private PathVectorProtocolResponse(boolean noInit) {}
    
    private static final PathVectorProtocolResponse defaultInstance;
    public static PathVectorProtocolResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public PathVectorProtocolResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse result;
      
      // Construct using de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse();
        return builder;
      }
      
      protected de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse.getDescriptor();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse getDefaultInstanceForType() {
        return de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse) {
          return mergeFrom((de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse other) {
        if (other == de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocolResponse)
    }
    
    static {
      defaultInstance = new PathVectorProtocolResponse(true);
      de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocolResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/path_vector_protoco" +
      "l.proto\022,de.uniluebeck.itm.uberlay.core." +
      "protocols.pvp\"\033\n\031PathVectorProtocolReque" +
      "st\"\034\n\032PathVectorProtocolResponseB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolRequest_descriptor,
              new java.lang.String[] { },
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest.class,
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolRequest.Builder.class);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_uberlay_core_protocols_pvp_PathVectorProtocolResponse_descriptor,
              new java.lang.String[] { },
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse.class,
              de.uniluebeck.itm.uberlay.core.protocols.pvp.PathVectorProtocol.PathVectorProtocolResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
